var config = {
	//div的id，默认：map
	target: "map",
	//坐标系，默认：EPSG:4326
	projection: "EPSG:4326",
	//分辨率,必填
	resolutions: [
		new Number(0.40312500015485435),
		new Number(0.35156250007742718),
		new Number(0.1757812500387135),
		new Number(0.0878906250193568),
		new Number(0.0439453125096784),
		new Number(0.0219726562548392),
		new Number(0.0109863281274196),
		new Number(0.0054931640637098),
		new Number(0.0027465820318549957),
		new Number(0.0013732910159274978),
		new Number(0.00068664549607834132),
		new Number(0.00034332275992416907),
		new Number(0.00017166136807812298),
		new Number(0.000085830684039061379),
		new Number(0.000042915342019530649),
		new Number(0.000021457682893727977),
		new Number(0.000010728841446864),
		new Number(0.0000053644207234319882),
		new Number(0.0000026822103617159941)
	],
	//地图初始范围,默认：[-180,-90,180,90]
	initExtent: [132.1337, 47.7040, 133.0000, 47.8689],
	centerPosition: [37.41, 8.82],
	proxyUrl: "",
	layersConf: [{
			ID: "0",
			PARENTID: null,
			name: "业务图层",
			SERVERTYPE: "",
			LAYERTYPE: "group",
			URL: "",
			TYPENAME: "",
			FORMAT: "",
			MATRIXSET: "",
			REQUEST: "",
			VERSION: "",
			SERVICE: "",
			STYLE: "",
			OPACITY: "",
			PROJECTION: "",
			ORIGINX: "",
			ORIGINY: "",
			TILEWIDTH: "",
			VISIBLE: "",
			ORDINAL: ""
		},
		{
			ID: "100",
			PARENTID: null,
			name: "背景图层",
			SERVERTYPE: "",
			LAYERTYPE: "group",
			URL: "",
			TYPENAME: "",
			FORMAT: "",
			MATRIXSET: "",
			REQUEST: "",
			VERSION: "",
			SERVICE: "",
			STYLE: "",
			OPACITY: "",
			PROJECTION: "",
			ORIGINX: "",
			ORIGINY: "",
			TILEWIDTH: "",
			VISIBLE: "",
			ORDINAL: ""
		},
		{
			ID: "2",
			PARENTID: "100",
			name: "天地图",
			SERVERTYPE: "",
			LAYERTYPE: "group",
			URL: "",
			TYPENAME: "",
			FORMAT: "",
			MATRIXSET: "",
			REQUEST: "",
			VERSION: "",
			SERVICE: "",
			STYLE: "",
			OPACITY: "",
			PROJECTION: "",
			ORIGINX: "",
			ORIGINY: "",
			TILEWIDTH: 256,
			VISIBLE: "",
			ORDINAL: "",
			checked: true
		},

		{
			ID: "3",
			PARENTID: "2",
			name: "影像",
			groupname: "base",
			SERVERTYPE: "",
			LAYERTYPE: "group",
			URL: "",
			TYPENAME: "",
			FORMAT: "",
			MATRIXSET: "",
			REQUEST: "",
			VERSION: "",
			SERVICE: "",
			STYLE: "",
			OPACITY: "",
			PROJECTION: "",
			ORIGINX: "",
			ORIGINY: "",
			TILEWIDTH: 256,
			VISIBLE: "",
			ORDINAL: ""
		},
		{
			ID: "4",
			PARENTID: "3",
			name: "注记",
			SERVERTYPE: "TDT",
			LAYERTYPE: "cia_c",
			URL: "http://t0.tianditu.gov.cn/LAYERTYPE/wmts/?tk=c1d6b49adb2ba817109873dbc13becb4",
			TYPENAME: "cia",
			FORMAT: "tiles",
			MATRIXSET: "c",
			REQUEST: "",
			VERSION: "",
			SERVICE: "",
			STYLE: "",
			OPACITY: 1,
			PROJECTION: "",
			ORIGINX: -180,
			ORIGINY: 90,
			TILEWIDTH: 256,
			VISIBLE: 0,
			ORDINAL: ""
		},
		{
			ID: "5",
			PARENTID: "3",
			name: "影像",
			SERVERTYPE: "TDT",
			LAYERTYPE: "img_c",
			URL: "http://t0.tianditu.gov.cn/LAYERTYPE/wmts/?tk=c1d6b49adb2ba817109873dbc13becb4",
			TYPENAME: "img",
			FORMAT: "tiles",
			MATRIXSET: "c",
			REQUEST: "",
			VERSION: "",
			SERVICE: "",
			STYLE: "",
			OPACITY: 1,
			PROJECTION: "",
			ORIGINX: -180,
			ORIGINY: 90,
			TILEWIDTH: 256,
			VISIBLE: 0,
			ORDINAL: "",
			checked: true
		},

		{
			ID: "6",
			PARENTID: "2",
			name: "矢量",
			groupname: "base",
			SERVERTYPE: "",
			LAYERTYPE: "group",
			URL: "",
			TYPENAME: "",
			FORMAT: "",
			MATRIXSET: "",
			REQUEST: "",
			VERSION: "",
			SERVICE: "",
			STYLE: "",
			OPACITY: "",
			PROJECTION: "",
			ORIGINX: "",
			ORIGINY: "",
			TILEWIDTH: 256,
			VISIBLE: "",
			ORDINAL: ""
		},
		{
			ID: "7",
			PARENTID: "6",
			name: "注记",
			SERVERTYPE: "TDT",
			LAYERTYPE: "cva_c",
			URL: "http://t0.tianditu.gov.cn/LAYERTYPE/wmts/",
			TYPENAME: "cva",
			FORMAT: "tiles",
			MATRIXSET: "c",
			REQUEST: "",
			VERSION: "",
			SERVICE: "",
			STYLE: "",
			OPACITY: 1,
			PROJECTION: "",
			ORIGINX: -180,
			ORIGINY: 90,
			TILEWIDTH: 256,
			VISIBLE: 0,
			ORDINAL: ""
		},
		{
			ID: "8",
			PARENTID: "6",
			name: "矢量",
			SERVERTYPE: "TDT",
			LAYERTYPE: "vec_c",
			URL: "http://t0.tianditu.gov.cn/LAYERTYPE/wmts/",
			TYPENAME: "vec",
			FORMAT: "tiles",
			MATRIXSET: "c",
			REQUEST: "",
			VERSION: "",
			SERVICE: "",
			STYLE: "",
			OPACITY: 1,
			PROJECTION: "",
			ORIGINX: -180,
			ORIGINY: 90,
			TILEWIDTH: 256,
			VISIBLE: 0,
			ORDINAL: ""
		},

		{
			ID: "9",
			PARENTID: "2",
			name: "地形",
			groupname: "base",
			SERVERTYPE: "",
			LAYERTYPE: "group",
			URL: "apServer",
			TYPENAME: "",
			FORMAT: "",
			MATRIXSET: "",
			REQUEST: "",
			VERSION: "",
			SERVICE: "",
			STYLE: "",
			OPACITY: "",
			PROJECTION: "",
			ORIGINX: "",
			ORIGINY: "",
			TILEWIDTH: 256,
			VISIBLE: 0,
			ORDINAL: ""
		},
		{
			ID: "10",
			PARENTID: "9",
			name: "注记",
			SERVERTYPE: "TDT",
			LAYERTYPE: "cta_c",
			URL: "http://t0.tianditu.gov.cn/LAYERTYPE/wmts/?tk=",
			TK: "",
			TYPENAME: "cta",
			FORMAT: "tiles",
			MATRIXSET: "c",
			REQUEST: "",
			VERSION: "",
			SERVICE: "",
			STYLE: "",
			OPACITY: 1,
			PROJECTION: "",
			ORIGINX: -180,
			ORIGINY: 90,
			TILEWIDTH: 256,
			VISIBLE: 0,
			ORDINAL: ""
		},
		{
			ID: "11",
			PARENTID: "9",
			name: "地形",
			SERVERTYPE: "TDT",
			LAYERTYPE: "ter_c",
			URL: "http://t0.tianditu.gov.cn/LAYERTYPE/wmts/",
			TYPENAME: "ter",
			FORMAT: "tiles",
			MATRIXSET: "c",
			REQUEST: "",
			VERSION: "",
			SERVICE: "",
			STYLE: "",
			OPACITY: 1,
			PROJECTION: "",
			ORIGINX: -180,
			ORIGINY: 90,
			TILEWIDTH: 256,
			VISIBLE: 0,
			ORDINAL: ""
		},
		{
			ID: "112",
			PARENTID: "3",
			name: "谷歌影像",
			SERVERTYPE: "googleMap",
			LAYERTYPE: "vec_c",
			URL: "",
			TYPENAME: "vec",
			FORMAT: "tiles",
			MATRIXSET: "c",
			REQUEST: "",
			VERSION: "",
			SERVICE: "",
			STYLE: "",
			OPACITY: 1,
			PROJECTION: "",
			ORIGINX: -180,
			ORIGINY: 90,
			TILEWIDTH: 256,
			VISIBLE: 0,
			ORDINAL: ""
		},
		{
			ID: "113",
			PARENTID: "3",
			name: "必应影像",
			SERVERTYPE: "binMap",
			LAYERTYPE: "vec_c",
			URL: "",
			TYPENAME: "vec",
			FORMAT: "tiles",
			MATRIXSET: "c",
			REQUEST: "",
			VERSION: "",
			SERVICE: "",
			STYLE: "",
			OPACITY: 1,
			PROJECTION: "",
			ORIGINX: -180,
			ORIGINY: 90,
			TILEWIDTH: 256,
			VISIBLE: 0,
			ORDINAL: ""
		},
		{
			ID: "114",
			PARENTID: "3",
			name: "Arcgis影像",
			SERVERTYPE: "arcgis",
			LAYERTYPE: "vec_c",
			URL: "",
			TYPENAME: "vec",
			FORMAT: "tiles",
			MATRIXSET: "c",
			REQUEST: "",
			VERSION: "",
			SERVICE: "",
			STYLE: "",
			OPACITY: 1,
			PROJECTION: "",
			ORIGINX: -180,
			ORIGINY: 90,
			TILEWIDTH: 256,
			VISIBLE: 1,
			ORDINAL: ""
		}
	],
	//鹰眼图层列表
	ovLayersConf: [{
			ID: "7",
			PARENTID: "6",
			name: "注记",
			SERVERTYPE: "TDT",
			LAYERTYPE: "cva_c",
			URL: "http://t0.tianditu.gov.cn/LAYERTYPE/wmts/",
			TYPENAME: "cva",
			FORMAT: "tiles",
			MATRIXSET: "c",
			REQUEST: "",
			VERSION: "",
			SERVICE: "",
			STYLE: "",
			OPACITY: 1,
			PROJECTION: "",
			ORIGINX: -180,
			ORIGINY: 90,
			TILEWIDTH: 256,
			VISIBLE: 1,
			ORDINAL: ""
		},
		{
			ID: "8",
			PARENTID: "6",
			name: "矢量",
			SERVERTYPE: "TDT",
			LAYERTYPE: "vec_c",
			URL: "http://t0.tianditu.gov.cn/LAYERTYPE/wmts/",
			TYPENAME: "vec",
			FORMAT: "tiles",
			MATRIXSET: "c",
			REQUEST: "",
			VERSION: "",
			SERVICE: "",
			STYLE: "",
			OPACITY: 1,
			PROJECTION: "",
			ORIGINX: -180,
			ORIGINY: 90,
			TILEWIDTH: 256,
			VISIBLE: 1,
			ORDINAL: ""
		}
	]
}